Update patch set 1
Patch Set 1:

Please see this sandbox job where I tried to test the revised macro

https://jenkins.acumos.org/sandbox/job/federation-maven-dl-merge-master/1/console

I don't know what this failure means but I'm sure it requires LF intervention to repair:

---> create-netrc.sh
ERROR: Credential not found.

Patch-set: 1