Update patch set 6
Patch Set 6:

I think still there are some setting missing. Getting below error.

https://jenkins.acumos.org/view/spark-model-runner/job/spark-model-runner-maven-javadoc-verify-master-openjdk8/5/console

https://jenkins.acumos.org/view/spark-model-runner/job/spark-model-runner-maven-docker-verify-master-mvn35-openjdk8/5/console

ERROR: not able to provide the file [ManagedFile: id=spark-model-runner-settings, targetLocation=, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator?
[PostBuildScript] - Executing post build scripts.

Patch-set: 6